plan_task:
  description: >
    Produce a list with {num_searches} terms to search on internet about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with {num_searches} relevant terms to search on internet in order to search relevant information about {topic}
  agent: research_planner

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
    Remember to mention the sources of the information retrieved.
  expected_output: >
    A list with {num_searches} paragraphs of the most relevant information about the term to search with the tools at your disposal.
  agent: research_assistant
  context:
    - plan_task

writing_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    Ask user input for more information is needed.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
    Remember to mention the sources of the information retrieved.
  agent: writer
  context:
    - research_task
